#登陆相关配置
login:
  #开放的模拟登陆api服务器地址 
  api: "http://www.zimo.wiki:8080/wisedu-unified-login-api-v1.0/api/login"

#用户组配置
users:
  #单个用户配置
  - user:
      #username 学号或者工号
      username: ''
      #password 密码
      password: ''
      #address 地址，定位信息
      address: 中国福建省XXXXXXXX
      #email 接受通知消息的邮箱
      email: XXXXXX@qq.com
      #school 学校全称
      school: XXXXXX
      lon: 'XX.XXXXXX'
      lat: 'XX.XXXXXX'
      photo: './photo.jpg'
      abnormalReason: ''

#今日校园相关配置
cpdaily:
  #表单组默认选项配置
  defaults:
    - default:
        #表单项标题
        title: 今天你的所在地是？
        #表单项类型，对应今日校园接口返回的fieldType字段，1代表文本，2代表单选，3代表多选，4代表图片
        type: 1
        #表单项默认值, 三级选项选择用 '/' 分隔
        value: 福建省/福州市/XXX
    - default:
        title: 今天你的体温是多少？
        type: 2
        value: 37.2℃及以下
    - default:
        title: 今天你的身体状况是？
        type: 2
        value: 健康
    - default:
        title: 近14天你或你的共同居住人是否有疫情中、高风险区域人员接触史？
        type: 2
        value: 否
    - default:
        title: 近14天你或你的共同居住人是否和确诊、疑似病人接触过？
        type: 2
        value: 否
    - default:
        title: 近14天你或你的共同居住人是否是确诊、疑似病例？
        type: 2
        value: 否
    - default:
        title: 你或你的共同居住人目前是否被医学隔离？
        type: 2
        value: 否
    - default:
        title: 今天你当地的健康码颜色是？
        type: 2
        value: 绿色
    - default:
        title: 本人是否承诺以上所填报的全部内容均属实、准确，不存在任何隐瞒与不实的情况，更无遗漏之处    
        type: 2
        value: 是


SMTP:
    smtp_from: '' # 邮件服务器登录用户名
    smtp_pass: '' # 邮件服务器登录密码
    apikey: '057294506049c2a06c6fa4' # 色图api
