# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # 每天北京时间8点执行，第二个0代表小时，以此类推，如：9点——'0 1 * * *''
    - cron: '0 0 * * *'

jobs:
  submit_user1:

    runs-on: ubuntu-latest
    environment: TUT # 此处填入环境名
    # 使用action运行本地api服务时打开
    # services:
    #   # Label used to access the service container
    #   wisedu-unified:
    #     # Docker Hub image
    #     image: registry.cn-shenzhen.aliyuncs.com/wisedu_api/wisedu_api:v1
    #     ports:
    #       # Maps port 6379 on service container to the host
    #       - 8080:8080

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Install dependencies
      run: | 
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Run code 
      env:
        # 模拟登录api地址
        login_api: ${{ secrets.login_api }}
        # 配置个人信息
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
        address: ${{ secrets.address }}
        school: ${{ secrets.school }}
        # 配置推送信息
        # ServerChan
        sckey: ${{ secrets.sckey }}
        # 使用的config.yml
        config: ${{secrets.config}}

      run: |
        python ./index.py $config


  submit_user2:

    runs-on: ubuntu-latest
    environment: Liao # 此处填入环境名
    # services:
    #   # Label used to access the service container
    #   wisedu-unified:
    #     # Docker Hub image
    #     image: registry.cn-shenzhen.aliyuncs.com/wisedu_api/wisedu_api:v1
    #     ports:
    #       # Maps port 6379 on service container to the host
    #       - 8080:8080

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Install dependencies
      run: | 
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Run code 
      env:
        # 模拟登录api地址
        login_api: ${{ secrets.login_api }}
        # 配置个人信息
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
        address: ${{ secrets.address }}
        school: ${{ secrets.school }}
        # 配置推送信息
        # ServerChan
        sckey: ${{ secrets.sckey }}
        # 使用的config.yml
        config: ${{secrets.config}}

      run: |
        python ./index.py $config
        
  submit_user3:

    runs-on: ubuntu-latest
    environment: ZD # 此处填入环境名
    # services:
    #   # Label used to access the service container
    #   wisedu-unified:
    #     # Docker Hub image
    #     image: registry.cn-shenzhen.aliyuncs.com/wisedu_api/wisedu_api:v1
    #     ports:
    #       # Maps port 6379 on service container to the host
    #       - 8080:8080

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Install dependencies
      run: | 
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Run code 
      env:
        # 模拟登录api地址
        login_api: ${{ secrets.login_api }}
        # 配置个人信息
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
        address: ${{ secrets.address }}
        school: ${{ secrets.school }}
        # 配置推送信息
        # ServerChan
        sckey: ${{ secrets.sckey }}
        # 使用的config.yml
        config: ${{secrets.config}}

      run: |
        python ./index.py $config
